[general]
live_config_reload = true
import = [
  "~/.dotfiles/alacritty/catppuccin/catppuccin-latte.toml"
]

[cursor.style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 14

[font.italic]
family = "JetBrainsMonoNL NF"

[font.bold]
family = "JetBrainsMonoNL NF"

[font.normal]
family = "JetBrainsMonoNL NF"

[window]
decorations = "buttonless"
# decorations = "none"
dynamic_padding = true
opacity = 1
blur = true

[window.padding]
x = 12
y = 8

[bell]
animation = 'EaseOutSine'
duration = 200
color = "#F5E0DC"

