import = [
  # Cattpuccin 
  # "~/.dotfiles/alacritty/catppuccin/catppuccin-latte.toml"
  # "~/.dotfiles/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.dotfiles/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "~/.dotfiles/alacritty/catppuccin/catppuccin-mocha.toml"
  # Everforest
  "~/.dotfiles/alacritty/everforest/everforest-dark-hard.toml"
  # "~/.dotfiles/alacritty/everforest/everforest-dark-medium.toml"
  # "~/.dotfiles/alacritty/everforest/everforest-dark-soft.toml"
  # "~/.dotfiles/alacritty/everforest/everforest-light-hard.toml"
  # "~/.dotfiles/alacritty/everforest/everforest-light-medium.toml"
  # "~/.dotfiles/alacritty/everforest/everforest-light-soft.toml"
]
live_config_reload = true

[cursor.style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 14

[font.italic]
family = "JetBrainsMonoNL Nerd Font"

[font.bold]
family = "JetBrainsMonoNL Nerd Font"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.96
blur = true

[window.padding]
x = 6
y = 6

[bell]
animation = 'EaseOutSine'
duration = 200
color = "#F5E0DC"
